'use strict';
// v2.1.0: แก้โหลดรายชื่อพนักงาน, ลบพนักงาน, ลบข้อมูลเก่า/เคลียร์ log และอ่าน attendance เก่าได้ดีขึ้น
const $=id=>document.getElementById(id);
const pad=n=>String(n).padStart(2,'0');
const todayKey=()=>new Date().toISOString().slice(0,10);
const fmtDateTime=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
const safeText=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const money=n=>Number(n||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
let app,auth,db,currentUser,currentEmployee=null,mediaStream=null,capturedDataUrl=null,currentPosition=null,deferredPrompt=null;
let companySettings={companyName:'ระบบลงเวลาออนไลน์',officeLat:null,officeLng:null,radiusMeters:100};
let lastAttendanceRows=[],lastPayrollRows=[],shiftCache=[],benefitCache=[];

function toast(msg,ms=3200){const t=$('toast'); if(!t) return alert(msg); t.textContent=msg; t.classList.remove('hidden'); setTimeout(()=>t.classList.add('hidden'),ms)}
function showPanel(id){['setupPanel','loginPanel','employeePanel','adminPanel'].forEach(x=>$(x)?.classList.add('hidden')); $(id)?.classList.remove('hidden')}
function setBusy(btn,busy,text){if(!btn)return; if(busy){btn.dataset.old=btn.textContent; btn.textContent=text||'กำลังทำงาน...'; btn.disabled=true}else{btn.textContent=btn.dataset.old||btn.textContent; btn.disabled=false}}
async function sha256(text){const data=new TextEncoder().encode(text); const hash=await crypto.subtle.digest('SHA-256',data); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function cfg(){return window.firebaseConfig||window.FIREBASE_CONFIG||null}
function firebaseReady(){const c=cfg(); return c&&c.apiKey&&!String(c.apiKey).startsWith('YOUR_')}
async function initFirebase(){if(!firebaseReady()){showPanel('setupPanel');return} app=firebase.initializeApp(cfg()); auth=firebase.auth(); db=firebase.firestore(); await auth.signInAnonymously(); currentUser=auth.currentUser; await loadSettings(); await restoreSession(); if(!currentEmployee) showPanel('loginPanel')}
async function logAudit(action,details={},employee=null){try{await db.collection('auditLogs').add({action,details,createdAt:firebase.firestore.FieldValue.serverTimestamp(),actorCode:employee?.employeeCode||currentEmployee?.employeeCode||'anonymous',actorName:employee?.fullName||currentEmployee?.fullName||'',userAgent:navigator.userAgent})}catch(e){console.warn('audit failed',e)}}
async function loadSettings(){try{const d=await db.collection('settings').doc('company').get(); if(d.exists) companySettings={...companySettings,...d.data()}; if($('companyName')) $('companyName').textContent=companySettings.companyName||'ระบบลงเวลาออนไลน์'}catch(e){console.warn(e)}}
async function restoreSession(){const id=localStorage.getItem('attendance.currentEmployeeId'); if(!id)return; try{const d=await db.collection('employees').doc(id).get(); if(d.exists&&d.data().active){currentEmployee={id:d.id,...d.data()}; currentEmployee.role==='admin'?showAdmin():showEmployee()}else localStorage.removeItem('attendance.currentEmployeeId')}catch(e){console.warn(e)}}
async function login(){const btn=$('loginBtn'); setBusy(btn,true,'กำลังเข้าสู่ระบบ...'); try{const code=$('loginCode').value.trim(), pin=$('loginPin').value.trim(); if(!code||!pin) throw new Error('กรุณากรอกรหัสพนักงานและ PIN'); const snap=await db.collection('employees').where('employeeCode','==',code).limit(1).get(); if(snap.empty) throw new Error('ไม่พบรหัสพนักงาน'); const doc=snap.docs[0], emp={id:doc.id,...doc.data()}; if(!emp.active) throw new Error('บัญชีนี้ถูกปิดใช้งาน'); if(emp.pinHash!==await sha256(pin)) throw new Error('PIN ไม่ถูกต้อง'); currentEmployee=emp; localStorage.setItem('attendance.currentEmployeeId',emp.id); await logAudit('LOGIN',{},emp); emp.role==='admin'?showAdmin():showEmployee()}catch(e){toast(e.message,5000)}finally{setBusy(btn,false)}}
async function seedAdmin(){const btn=$('seedAdminBtn'); setBusy(btn,true,'กำลังสร้าง...'); try{const existing=await db.collection('employees').where('role','==','admin').limit(1).get(); if(!existing.empty) throw new Error('มีแอดมินอยู่แล้ว'); const shift=await ensureDefaultShift(); await db.collection('employees').add({employeeCode:'admin',fullName:'ผู้ดูแลระบบ',department:'Admin',position:'Admin',role:'admin',active:true,pinHash:await sha256('admin123'),payType:'monthly',payCycle:'monthly',hourlyRate:0,dailyRate:0,monthlySalary:0,otMultiplier:1.5,shiftId:shift.id,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()}); toast('สร้างแอดมินแล้ว: admin / admin123')}catch(e){toast(e.message,5000)}finally{setBusy(btn,false)}}
function logout(){stopCamera(); localStorage.removeItem('attendance.currentEmployeeId'); currentEmployee=null; capturedDataUrl=null; currentPosition=null; if($('loginPin')) $('loginPin').value=''; showPanel('loginPanel')}

async function ensureDefaultShift(){let s=await db.collection('shifts').limit(1).get(); if(!s.empty) return {id:s.docs[0].id,...s.docs[0].data()}; const ref=await db.collection('shifts').add({name:'กะปกติ 08:00-17:00',start:'08:00',end:'17:00',breakMinutes:60,regularHours:8,active:true,createdAt:firebase.firestore.FieldValue.serverTimestamp()}); return {id:ref.id,name:'กะปกติ 08:00-17:00',start:'08:00',end:'17:00',breakMinutes:60,regularHours:8,active:true}}
async function getShifts(){const snap=await db.collection('shifts').orderBy('name').get(); shiftCache=snap.docs.map(d=>({id:d.id,...d.data()})); return shiftCache}
async function getBenefits(){const snap=await db.collection('benefits').where('active','==',true).get(); benefitCache=snap.docs.map(d=>({id:d.id,...d.data()})); return benefitCache}
function getShift(id){return shiftCache.find(s=>s.id===id)||shiftCache[0]||{start:'08:00',end:'17:00',breakMinutes:60,regularHours:8,name:'กะปกติ'}}

async function showEmployee(){showPanel('employeePanel'); $('empName').textContent=currentEmployee.fullName; $('empDetail').textContent=`${currentEmployee.employeeCode} • ${currentEmployee.department||'-'} • ${currentEmployee.position||'-'}`; setUserDefaultDates(); await refreshMyStatus(); await loadMyHistory()}
function setUserDefaultDates(){const t=todayKey(); ['userOtDate','leaveStart','leaveEnd'].forEach(id=>{if($(id)) $(id).value=t})}
async function refreshMyStatus(){const rows=await getAttendanceRows(currentEmployee.id,todayKey(),todayKey()); const last=rows.sort((a,b)=>recMillis(a)-recMillis(b)).at(-1); $('todayStatus').textContent=!last?'วันนี้ยังไม่ได้ลงเวลา':`ล่าสุด: ${last.type==='IN'?'เข้างาน':'ออกงาน'} เวลา ${displayTime(last)}`}
async function loadMyHistory(){try{const rows=await getAttendanceRows(currentEmployee.id,null,null); const daily=pairAttendance(rows).slice(0,30); $('myHistory').innerHTML=daily.map(r=>renderDailyItem(r,false)).join('')||'<p class="muted">ยังไม่มีประวัติ</p>'}catch(e){console.error(e); $('myHistory').innerHTML=`<p class="muted">โหลดประวัติไม่สำเร็จ: ${safeText(e.message)}</p>`}}
async function startCamera(){try{stopCamera(); mediaStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false}); $('camera').srcObject=mediaStream}catch(e){toast('เปิดกล้องไม่ได้: '+e.message,5000)}}
function stopCamera(){if(mediaStream){mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null}}
async function getGPS(){return new Promise((resolve,reject)=>{if(!navigator.geolocation) return reject(new Error('อุปกรณ์นี้ไม่รองรับ GPS')); navigator.geolocation.getCurrentPosition(pos=>{currentPosition={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy}; if($('gpsStatus')) $('gpsStatus').textContent=`GPS: ${currentPosition.lat.toFixed(6)}, ${currentPosition.lng.toFixed(6)} ±${Math.round(currentPosition.accuracy)}m`; resolve(currentPosition)},err=>reject(new Error(err.message||'ไม่ได้รับอนุญาตตำแหน่ง')),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
async function captureSelfie(){const video=$('camera'); if(!mediaStream) throw new Error('กรุณาเปิดกล้องก่อน'); if(!currentEmployee) throw new Error('กรุณาเข้าสู่ระบบก่อน'); await getGPS(); const sw=video.videoWidth||720, sh=video.videoHeight||960, maxW=260, scale=Math.min(1,maxW/sw), w=Math.round(sw*scale), h=Math.round(sh*scale); const canvas=$('snapshot'); canvas.width=w; canvas.height=h; const ctx=canvas.getContext('2d'); ctx.drawImage(video,0,0,w,h); const stamp=[currentEmployee.fullName,currentEmployee.employeeCode,fmtDateTime(new Date()),`GPS: ${currentPosition.lat.toFixed(6)}, ${currentPosition.lng.toFixed(6)}`]; const boxH=74; ctx.fillStyle='rgba(0,0,0,.68)'; ctx.fillRect(0,h-boxH,w,boxH); ctx.fillStyle='#fff'; ctx.font='11px sans-serif'; stamp.forEach((s,i)=>ctx.fillText(s,8,h-boxH+15+i*16)); capturedDataUrl=canvas.toDataURL('image/jpeg',0.22); const bytes=Math.round(capturedDataUrl.length*3/4); if(bytes>650000){capturedDataUrl=null; throw new Error('รูปยังใหญ่เกินไป กรุณาถ่ายใหม่')} $('preview').src=capturedDataUrl; $('preview').classList.remove('hidden'); toast('ถ่ายรูปและดึงตำแหน่งแล้ว')}
function distanceMeters(lat1,lng1,lat2,lng2){const R=6371000,toRad=x=>x*Math.PI/180,dLat=toRad(lat2-lat1),dLng=toRad(lng2-lng1); const a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLng/2)**2; return 2*R*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
async function clock(type){const btn=type==='IN'?$('clockInBtn'):$('clockOutBtn'); setBusy(btn,true,'กำลังบันทึก...'); try{if(!capturedDataUrl) throw new Error('ต้องถ่ายรูปหน้าตัวเองก่อนลงเวลา'); if(!currentPosition) await getGPS(); let dist=null,inGeo=null; if(companySettings.officeLat&&companySettings.officeLng){dist=distanceMeters(currentPosition.lat,currentPosition.lng,Number(companySettings.officeLat),Number(companySettings.officeLng)); inGeo=dist<=Number(companySettings.radiusMeters||100)} const now=new Date(); const data={employeeId:currentEmployee.id,employeeCode:currentEmployee.employeeCode,fullName:currentEmployee.fullName,type,source:'EMPLOYEE',dateKey:todayKey(),createdAt:firebase.firestore.FieldValue.serverTimestamp(),clientTime:now.toISOString(),clientTimeText:fmtDateTime(now),photoPath:'firestore-base64',photoURL:capturedDataUrl,photoMode:'base64',latitude:currentPosition.lat,longitude:currentPosition.lng,accuracy:currentPosition.accuracy,mapUrl:`https://maps.google.com/?q=${currentPosition.lat},${currentPosition.lng}`,distanceMeters:dist,inGeofence:inGeo,userAgent:navigator.userAgent}; await Promise.race([db.collection('attendance').add(data),new Promise((_,rej)=>setTimeout(()=>rej(new Error('บันทึกช้าเกินไป กรุณาเช็กอินเทอร์เน็ตแล้วลองใหม่')),20000))]); await logAudit(type==='IN'?'CLOCK_IN':'CLOCK_OUT',{employeeCode:currentEmployee.employeeCode,inGeofence:inGeo,distanceMeters:dist}); capturedDataUrl=null; currentPosition=null; $('preview').removeAttribute('src'); $('preview').classList.add('hidden'); if($('gpsStatus')) $('gpsStatus').textContent=''; toast('บันทึกสำเร็จ'); await refreshMyStatus(); await loadMyHistory()}catch(e){console.error(e); toast('บันทึกไม่สำเร็จ: '+e.message,6000)}finally{setBusy(btn,false)}}
async function autoClock(){const rows=await getAttendanceRows(currentEmployee.id,todayKey(),todayKey()); const last=rows.sort((a,b)=>recMillis(a)-recMillis(b)).at(-1); await clock(!last||last.type==='OUT'?'IN':'OUT')}
async function submitOt(){const btn=$('submitOtBtn'); setBusy(btn,true,'กำลังส่ง...'); try{const dateKey=$('userOtDate').value, hours=Number($('userOtHours').value||0), reason=$('userOtReason').value.trim(); if(!dateKey||hours<=0||!reason) throw new Error('กรุณากรอกวันที่ ชั่วโมง และเหตุผล OT'); await db.collection('otRequests').add({employeeId:currentEmployee.id,employeeCode:currentEmployee.employeeCode,fullName:currentEmployee.fullName,dateKey,hours,reason,status:'pending',createdAt:firebase.firestore.FieldValue.serverTimestamp()}); await logAudit('SUBMIT_OT',{dateKey,hours}); toast('ส่งคำขอ OT แล้ว')}catch(e){toast(e.message,5000)}finally{setBusy(btn,false)}}
async function submitLeave(){const btn=$('submitLeaveBtn'); setBusy(btn,true,'กำลังส่ง...'); try{const type=$('leaveType').value,start=$('leaveStart').value,end=$('leaveEnd').value,reason=$('leaveReason').value.trim(); if(!start||!end||!reason) throw new Error('กรุณากรอกข้อมูลวันลา'); await db.collection('leaveRequests').add({employeeId:currentEmployee.id,employeeCode:currentEmployee.employeeCode,fullName:currentEmployee.fullName,type,startDate:start,endDate:end,reason,status:'pending',createdAt:firebase.firestore.FieldValue.serverTimestamp()}); await logAudit('SUBMIT_LEAVE',{type,start,end}); toast('ส่งคำขอลาแล้ว')}catch(e){toast(e.message,5000)}finally{setBusy(btn,false)}}

async function safeRun(name,fn){try{return await fn()}catch(e){console.error(name,e); toast(`${name}: ${e.message}`,6000)}}
async function showAdmin(){showPanel('adminPanel'); $('adminName').textContent=`${currentEmployee.fullName} (${currentEmployee.employeeCode})`; setDefaultDates(); await safeRun('โหลดตั้งค่าหลัก',async()=>{await Promise.all([getShifts(),getBenefits(),loadSettings()]); fillShiftSelect(); fillSettings()}); await Promise.all([safeRun('โหลดภาพรวมวันนี้',loadTodayAdmin),safeRun('โหลดรายชื่อพนักงาน',loadEmployees),safeRun('โหลดปฏิทิน',loadCalendar),safeRun('โหลด OT',loadOt),safeRun('โหลดวันลา',loadLeave),safeRun('โหลดกะงาน',loadShifts),safeRun('โหลดสวัสดิการ',loadBenefits)])}
function setDefaultDates(){const t=todayKey(); ['attStart','attEnd','payStart','payEnd','corrDate','calDate'].forEach(id=>{if($(id)) $(id).value=t}); if($('payStart')) $('payStart').value=t.slice(0,8)+'01'; if($('attStart')) $('attStart').value=t.slice(0,8)+'01'; if($('corrTime')) $('corrTime').value='08:00'}
function switchTab(tab){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); document.querySelectorAll('.tab').forEach(el=>el.classList.add('hidden')); $('tab'+tab[0].toUpperCase()+tab.slice(1))?.classList.remove('hidden')}
function normalizeAttendance(id,r){const t=recTime(r); const dk=r.dateKey||(t?new Date(t.getTime()-t.getTimezoneOffset()*60000).toISOString().slice(0,10):todayKey()); return {id,...r,dateKey:dk,employeeId:r.employeeId||r.empId||r.employeeCode||'unknown',employeeCode:r.employeeCode||r.code||'',fullName:r.fullName||r.employeeName||r.name||''}}
async function getAttendanceRows(employeeId=null,start=null,end=null){let snap=await db.collection('attendance').get(); let rows=snap.docs.map(d=>normalizeAttendance(d.id,d.data())); if(employeeId){const empCode=currentEmployee?.id===employeeId?currentEmployee.employeeCode:null; rows=rows.filter(r=>r.employeeId===employeeId||r.employeeCode===empCode)} if(start) rows=rows.filter(r=>(r.dateKey||'')>=start); if(end) rows=rows.filter(r=>(r.dateKey||'')<=end); return rows}
function recTime(r){if(r.overrideTime) return new Date(r.overrideTime.replace(' ','T')); if(r.createdAt?.toDate) return r.createdAt.toDate(); if(r.clientTime) return new Date(r.clientTime); return null}
function recMillis(r){return recTime(r)?.getTime?.()||0}
function displayTime(r){const d=recTime(r); return d?fmtDateTime(d):'-'}
function pairAttendance(rows){const map={}; rows.forEach(r=>{const empKey=r.employeeId||r.employeeCode||'unknown'; const key=`${empKey}_${r.dateKey||todayKey()}`; (map[key]||={employeeId:r.employeeId||empKey,employeeCode:r.employeeCode||'',fullName:r.fullName||'',dateKey:r.dateKey||todayKey(),records:[]}).records.push(r)}); return Object.values(map).map(g=>{g.records.sort((a,b)=>recMillis(a)-recMillis(b)); const ins=g.records.filter(r=>r.type==='IN'), outs=g.records.filter(r=>r.type==='OUT'); g.firstIn=ins[0]||null; g.lastOut=outs.at(-1)||null; g.photoURL=g.firstIn?.photoURL||g.lastOut?.photoURL||''; g.mapUrl=g.firstIn?.mapUrl||g.lastOut?.mapUrl||''; g.inGeofence=g.firstIn?.inGeofence; g.distanceMeters=g.firstIn?.distanceMeters; g.workHours=(g.firstIn&&g.lastOut)?Math.max(0,(recMillis(g.lastOut)-recMillis(g.firstIn))/36e5):0; return g}).sort((a,b)=>String(b.dateKey+b.employeeCode).localeCompare(String(a.dateKey+a.employeeCode)))}
function renderDailyItem(r,admin){const img=r.photoURL?`<img src="${r.photoURL}" class="thumb" loading="lazy">`:''; const geo=r.inGeofence===null||r.inGeofence===undefined?'':`<span class="badge ${r.inGeofence?'good':'bad'}">${r.inGeofence?'ในพื้นที่':'นอกพื้นที่'} ${r.distanceMeters?Math.round(r.distanceMeters)+'m':''}</span>`; return `<div class="item"><div>${img}<b>${safeText(r.employeeCode)} - ${safeText(r.fullName)}</b><br><span class="muted">${r.dateKey} • เข้า ${r.firstIn?displayTime(r.firstIn).slice(11):'-'} • ออก ${r.lastOut?displayTime(r.lastOut).slice(11):'-'} • ${r.workHours.toFixed(2)} ชม.</span><br>${geo} <span class="badge">${r.records.length} รายการ</span></div><div class="row-actions">${r.mapUrl?`<a href="${r.mapUrl}" target="_blank"><button class="ghost">แผนที่</button></a>`:''}${admin?`<button class="ghost" onclick="copyText('${r.employeeId}')">คัดลอก ID</button>`:''}</div></div>`}
window.copyText=async t=>{await navigator.clipboard.writeText(t); toast('คัดลอกแล้ว')};
async function loadTodayAdmin(){const rows=await getAttendanceRows(null,todayKey(),todayKey()); const daily=pairAttendance(rows); $('todaySummary').innerHTML=`<div class="stat"><b>${daily.length}</b><span>คนลงเวลา</span></div><div class="stat"><b>${daily.filter(x=>x.firstIn).length}</b><span>เข้างาน</span></div><div class="stat"><b>${daily.filter(x=>x.lastOut).length}</b><span>ออกงาน</span></div><div class="stat"><b>${daily.filter(x=>x.inGeofence===false).length}</b><span>นอกพื้นที่</span></div>`; $('todayList').innerHTML=daily.map(r=>renderDailyItem(r,true)).join('')||'<p class="muted">วันนี้ยังไม่มีข้อมูล</p>'}

function fillShiftSelect(){const sel=$('empShiftId'); if(!sel)return; sel.innerHTML=shiftCache.map(s=>`<option value="${s.id}">${safeText(s.name)}</option>`).join('')}
async function loadEmployees(){try{await getShifts(); fillShiftSelect(); const snap=await db.collection('employees').get(); const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.employeeCode||'').localeCompare(String(b.employeeCode||''))); $('employeeList').innerHTML=rows.map(e=>`<div class="item"><b>${safeText(e.employeeCode)} - ${safeText(e.fullName)}</b><br><span class="muted">${safeText(e.department)} • ${safeText(e.position)} • ${e.role||'employee'} • ${payTypeText(e.payType)} • ${e.payCycle==='biweekly'?'ราย 14 วัน':'รายเดือน'} • ${safeText(getShift(e.shiftId)?.name||'-')}</span><br><span class="badge ${e.active!==false?'good':'bad'}">${e.active!==false?'ใช้งาน':'ปิด'}</span><div class="row-actions"><button onclick="editEmployee('${e.id}')" class="warning">แก้ไข</button><button onclick="toggleEmployee('${e.id}',${e.active!==false?'false':'true'})" class="ghost">${e.active!==false?'ปิดใช้งาน':'เปิดใช้งาน'}</button><button onclick="deleteEmployee('${e.id}','${safeText(e.employeeCode)}')" class="danger">ลบ</button></div></div>`).join('')||'<p class="muted">ยังไม่มีพนักงาน</p>'}catch(e){console.error(e); $('employeeList').innerHTML=`<p class="muted">โหลดรายชื่อพนักงานไม่สำเร็จ: ${safeText(e.message)}</p>`}}
function payTypeText(v){return v==='monthly'?'เงินเดือน':v==='daily'?'รายวัน':'รายชั่วโมง'}
function clearEmployeeForm(){['empIdEdit','empCode','empFullName','empDept','empPosition','empPin'].forEach(id=>{if($(id))$(id).value=''}); $('empRole').value='employee'; $('empPayType').value='hourly'; $('empPayCycle').value='monthly'; $('empHourly').value='0'; $('empDaily').value='0'; $('empMonthly').value='0'; $('empOt').value='1.5'; if($('empShiftId')&&shiftCache[0]) $('empShiftId').value=shiftCache[0].id; $('empActive').checked=true}
window.editEmployee=async id=>{const d=await db.collection('employees').doc(id).get(), e={id:d.id,...d.data()}; $('empIdEdit').value=e.id; $('empCode').value=e.employeeCode||''; $('empFullName').value=e.fullName||''; $('empDept').value=e.department||''; $('empPosition').value=e.position||''; $('empRole').value=e.role||'employee'; $('empPayType').value=e.payType||'hourly'; $('empPayCycle').value=e.payCycle||'monthly'; $('empHourly').value=e.hourlyRate||0; $('empDaily').value=e.dailyRate||0; $('empMonthly').value=e.monthlySalary||0; $('empOt').value=e.otMultiplier||1.5; if(e.shiftId) $('empShiftId').value=e.shiftId; $('empActive').checked=!!e.active; $('empPin').value=''; toast('โหลดข้อมูลเข้าฟอร์มแล้ว')};
window.toggleEmployee=async(id,active)=>{await db.collection('employees').doc(id).update({active,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}); await logAudit('TOGGLE_EMPLOYEE',{id,active}); loadEmployees()};
window.deleteEmployee=async(id,code)=>{if(!confirm(`ยืนยันลบพนักงาน ${code||id}?
ข้อมูลเวลาเข้าออกเดิมจะไม่ถูกลบ`))return; try{await db.collection('employees').doc(id).delete(); await logAudit('DELETE_EMPLOYEE',{id,code}); toast('ลบพนักงานแล้ว'); await loadEmployees()}catch(e){console.error(e); toast('ลบพนักงานไม่สำเร็จ: '+e.message,6000)}};
async function saveEmployee(){const id=$('empIdEdit').value, code=$('empCode').value.trim(), name=$('empFullName').value.trim(), pin=$('empPin').value.trim(); if(!code||!name)return toast('กรุณากรอกรหัสและชื่อ'); if(!id&&!pin)return toast('พนักงานใหม่ต้องมี PIN'); const data={employeeCode:code,fullName:name,department:$('empDept').value.trim(),position:$('empPosition').value.trim(),role:$('empRole').value,active:$('empActive').checked,payType:$('empPayType').value,payCycle:$('empPayCycle').value,hourlyRate:Number($('empHourly').value||0),dailyRate:Number($('empDaily').value||0),monthlySalary:Number($('empMonthly').value||0),otMultiplier:Number($('empOt').value||1.5),shiftId:$('empShiftId').value||null,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}; if(pin)data.pinHash=await sha256(pin); if(id) await db.collection('employees').doc(id).update(data); else await db.collection('employees').add({...data,createdAt:firebase.firestore.FieldValue.serverTimestamp()}); await logAudit(id?'UPDATE_EMPLOYEE':'ADD_EMPLOYEE',{code}); clearEmployeeForm(); loadEmployees(); toast('บันทึกพนักงานแล้ว')}

async function loadAttendance(){const rows=await getAttendanceRows(null,$('attStart').value,$('attEnd').value); lastAttendanceRows=pairAttendance(rows); $('attendanceList').innerHTML=lastAttendanceRows.map(r=>renderDailyItem(r,true)).join('')||'<p class="muted">ไม่พบข้อมูล</p>'}
async function saveCorrection(){const code=$('corrEmpCode').value.trim(), reason=$('corrReason').value.trim(); if(!code||!reason)return toast('กรอกรหัสพนักงานและเหตุผล'); const empSnap=await db.collection('employees').where('employeeCode','==',code).limit(1).get(); if(empSnap.empty)return toast('ไม่พบพนักงาน'); const doc=empSnap.docs[0], e={id:doc.id,...doc.data()}; const overrideTime=`${$('corrDate').value} ${$('corrTime').value}:00`; await db.collection('attendance').add({employeeId:e.id,employeeCode:e.employeeCode,fullName:e.fullName,type:$('corrType').value,source:'ADMIN_CORRECTION',dateKey:$('corrDate').value,overrideTime,reason,createdAt:firebase.firestore.FieldValue.serverTimestamp(),correctedBy:currentEmployee.employeeCode}); await logAudit('CORRECT_ATTENDANCE',{employeeCode:code,overrideTime,reason}); toast('บันทึกการแก้ไขแล้ว'); loadAttendance()}

async function loadShifts(){const shifts=await getShifts(); fillShiftSelect(); $('shiftList').innerHTML=shifts.map(s=>`<div class="item"><b>${safeText(s.name)}</b><br><span class="muted">${s.start} - ${s.end} • พัก ${s.breakMinutes||0} นาที • ปกติ ${s.regularHours||8} ชม.</span><div class="row-actions"><button class="warning" onclick="editShift('${s.id}')">แก้ไข</button></div></div>`).join('')||'<p class="muted">ยังไม่มีกะ</p>'}
window.editShift=id=>{const s=shiftCache.find(x=>x.id===id); if(!s)return; $('shiftIdEdit').value=s.id; $('shiftName').value=s.name; $('shiftStart').value=s.start; $('shiftEnd').value=s.end; $('shiftBreak').value=s.breakMinutes||0; $('shiftRegular').value=s.regularHours||8};
function clearShift(){['shiftIdEdit','shiftName'].forEach(id=>$(id).value=''); $('shiftStart').value='08:00'; $('shiftEnd').value='17:00'; $('shiftBreak').value=60; $('shiftRegular').value=8}
async function saveShift(){const id=$('shiftIdEdit').value; const data={name:$('shiftName').value.trim(),start:$('shiftStart').value,end:$('shiftEnd').value,breakMinutes:Number($('shiftBreak').value||0),regularHours:Number($('shiftRegular').value||8),active:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}; if(!data.name||!data.start||!data.end)return toast('กรอกชื่อกะและเวลา'); if(id) await db.collection('shifts').doc(id).update(data); else await db.collection('shifts').add({...data,createdAt:firebase.firestore.FieldValue.serverTimestamp()}); await logAudit('SAVE_SHIFT',data); clearShift(); loadShifts(); toast('บันทึกกะแล้ว')}

async function loadOt(){const snap=await db.collection('otRequests').orderBy('dateKey','desc').limit(120).get(); const rows=snap.docs.map(d=>({id:d.id,...d.data()})); $('otList').innerHTML=rows.map(o=>`<div class="item"><b>${safeText(o.employeeCode)} ${safeText(o.fullName)}</b><br><span class="muted">${o.dateKey} • ขอ ${o.hours} ชม. • ${safeText(o.reason)}</span><br><span class="badge ${o.status==='approved'?'good':o.status==='rejected'?'bad':''}">${safeText(o.status)}</span><div class="row-actions"><button class="good" onclick="approveOt('${o.id}',true)">อนุมัติ</button><button class="danger" onclick="approveOt('${o.id}',false)">ไม่อนุมัติ</button></div></div>`).join('')||'<p class="muted">ไม่มีคำขอ OT</p>'}
window.approveOt=async(id,ok)=>{await db.collection('otRequests').doc(id).update({status:ok?'approved':'rejected',approvedBy:currentEmployee.employeeCode,approvedAt:firebase.firestore.FieldValue.serverTimestamp()}); await logAudit(ok?'APPROVE_OT':'REJECT_OT',{id}); loadOt()};
async function loadLeave(){const snap=await db.collection('leaveRequests').orderBy('createdAt','desc').limit(120).get(); const rows=snap.docs.map(d=>({id:d.id,...d.data()})); $('leaveList').innerHTML=rows.map(l=>`<div class="item"><b>${safeText(l.employeeCode)} ${safeText(l.fullName)}</b><br><span class="muted">${leaveText(l.type)} • ${l.startDate} ถึง ${l.endDate} • ${safeText(l.reason)}</span><br><span class="badge ${l.status==='approved'?'good':l.status==='rejected'?'bad':''}">${safeText(l.status)}</span><div class="row-actions"><button class="good" onclick="approveLeave('${l.id}',true)">อนุมัติ</button><button class="danger" onclick="approveLeave('${l.id}',false)">ไม่อนุมัติ</button></div></div>`).join('')||'<p class="muted">ไม่มีคำขอลา</p>'}
function leaveText(t){return t==='sick'?'ลาป่วย':t==='vacation'?'ลาพักร้อน':'ลากิจ'}
window.approveLeave=async(id,ok)=>{await db.collection('leaveRequests').doc(id).update({status:ok?'approved':'rejected',approvedBy:currentEmployee.employeeCode,approvedAt:firebase.firestore.FieldValue.serverTimestamp()}); await logAudit(ok?'APPROVE_LEAVE':'REJECT_LEAVE',{id}); loadLeave()};

async function loadCalendar(){const snap=await db.collection('companyCalendar').orderBy('dateKey','desc').limit(120).get(); const rows=snap.docs.map(d=>({id:d.id,...d.data()})); $('calendarList').innerHTML=rows.map(c=>`<div class="item"><b>${safeText(c.dateKey)} - ${safeText(c.title)}</b><br><span class="muted">${safeText(c.type)} • ${c.isPaid?'มีค่าจ้าง':'ไม่มีค่าจ้าง'}</span><div class="row-actions"><button class="danger" onclick="deleteCalendar('${c.id}')">ลบ</button></div></div>`).join('')||'<p class="muted">ยังไม่มีรายการปฏิทิน</p>'}
async function saveCalendar(){const data={dateKey:$('calDate').value,title:$('calTitle').value.trim(),type:$('calType').value,isPaid:$('calPaid').checked,createdAt:firebase.firestore.FieldValue.serverTimestamp()}; if(!data.dateKey||!data.title)return toast('กรอกวันที่และชื่อรายการ'); await db.collection('companyCalendar').add(data); await logAudit('SAVE_CALENDAR',data); $('calTitle').value=''; loadCalendar()}
window.deleteCalendar=async id=>{await db.collection('companyCalendar').doc(id).delete(); await logAudit('DELETE_CALENDAR',{id}); loadCalendar()};
async function loadBenefits(){const snap=await db.collection('benefits').orderBy('name').get(); benefitCache=snap.docs.map(d=>({id:d.id,...d.data()})); $('benefitList').innerHTML=benefitCache.map(b=>`<div class="item"><b>${safeText(b.name)}</b><br><span class="muted">${money(b.amount)} บาท • ${b.mode==='perWorkday'?'ตามวันทำงาน':'Fix รายเดือน'}</span><br><span class="badge ${b.active?'good':'bad'}">${b.active?'ใช้งาน':'ปิด'}</span></div>`).join('')||'<p class="muted">ยังไม่มีสวัสดิการ</p>'}
async function saveBenefit(){const data={name:$('benefitName').value.trim(),amount:Number($('benefitAmount').value||0),mode:$('benefitMode').value,active:$('benefitActive').checked,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}; if(!data.name||data.amount<=0)return toast('กรอกชื่อและจำนวนเงิน'); const id=$('benefitIdEdit').value; if(id) await db.collection('benefits').doc(id).update(data); else await db.collection('benefits').add({...data,createdAt:firebase.firestore.FieldValue.serverTimestamp()}); await logAudit('SAVE_BENEFIT',data); $('benefitName').value=''; $('benefitAmount').value=''; loadBenefits(); toast('บันทึกสวัสดิการแล้ว')}

function fillSettings(){$('setCompany').value=companySettings.companyName||''; $('setRadius').value=companySettings.radiusMeters||100; $('setLat').value=companySettings.officeLat||''; $('setLng').value=companySettings.officeLng||''}
async function saveSettings(){companySettings={companyName:$('setCompany').value.trim()||'ระบบลงเวลาออนไลน์',radiusMeters:Number($('setRadius').value||100),officeLat:$('setLat').value?Number($('setLat').value):null,officeLng:$('setLng').value?Number($('setLng').value):null}; await db.collection('settings').doc('company').set({...companySettings,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}); await logAudit('UPDATE_SETTINGS',companySettings); await loadSettings(); toast('บันทึกตั้งค่าแล้ว')}
async function useCurrentLocation(){const p=await getGPS(); $('setLat').value=p.lat.toFixed(6); $('setLng').value=p.lng.toFixed(6)}
async function deleteCollection(name,limit=450){if(!confirm(`ยืนยันลบข้อมูล ${name} ทั้งหมด?`))return; let total=0; try{while(true){const snap=await db.collection(name).limit(limit).get(); if(snap.empty)break; const batch=db.batch(); snap.docs.forEach(d=>batch.delete(d.ref)); await batch.commit(); total+=snap.size; if(snap.size<limit)break} if(name!=='auditLogs') await logAudit('CLEAR_COLLECTION',{name,count:total}); toast(`ลบ ${name} แล้ว ${total} รายการ`); if(name==='attendance'){await loadTodayAdmin(); await loadAttendance()} if(name==='auditLogs'&&$('auditList')) $('auditList').innerHTML='<p class="muted">เคลียร์ log แล้ว</p>'}catch(e){console.error(e); toast(`ลบ ${name} ไม่สำเร็จ: ${e.message}`,7000)}}

async function runPayroll(){const start=$('payStart').value,end=$('payEnd').value; const [empSnap,attSnap,otSnap,benefitsSnap]=await Promise.all([db.collection('employees').get(),db.collection('attendance').where('dateKey','>=',start).where('dateKey','<=',end).get(),db.collection('otRequests').where('dateKey','>=',start).where('dateKey','<=',end).where('status','==','approved').get(),db.collection('benefits').where('active','==',true).get()]); const employees=empSnap.docs.map(d=>({id:d.id,...d.data()})).filter(e=>e.role!=='admin'&&e.active!==false); const records=attSnap.docs.map(d=>({id:d.id,...d.data()})); const ots=otSnap.docs.map(d=>({id:d.id,...d.data()})); const benefits=benefitsSnap.docs.map(d=>({id:d.id,...d.data()})); await getShifts(); lastPayrollRows=employees.map(e=>calcPayroll(e,records.filter(r=>r.employeeId===e.id),ots.filter(o=>o.employeeId===e.id),benefits,start,end)).filter(r=>r.workDays>0||r.basePay>0); $('payrollList').innerHTML=lastPayrollRows.map(r=>`<div class="item"><b>${safeText(r.employeeCode)} ${safeText(r.fullName)}</b><br><span class="muted">${payTypeText(r.payType)} • ${r.payCycle==='biweekly'?'ราย 14 วัน':'รายเดือน'} • วันทำงาน ${r.workDays} • ปกติ ${r.regularHours.toFixed(2)} ชม. • OT อนุมัติ ${r.approvedOtHours.toFixed(2)} ชม.</span><br>ฐาน ${money(r.basePay)} + OT ${money(r.otPay)} + สวัสดิการ ${money(r.benefitsPay)} - หักสาย ${money(r.lateDeduction)} = <b>${money(r.netPay)} บาท</b><div class="row-actions"><button class="secondary" onclick="printSlip('${r.employeeId}')">พิมพ์ Slip</button></div></div>`).join('')||'<p class="muted">ไม่พบข้อมูลเงินเดือน</p>'}
function calcPayroll(e,rows,ots,benefits,start,end){const daily=pairAttendance(rows); const shift=getShift(e.shiftId); let workDays=0,regularHours=0,lateMinutes=0; daily.forEach(d=>{if(!d.firstIn||!d.lastOut)return; workDays++; const hrs=d.workHours; regularHours+=Math.min(hrs,Number(shift.regularHours||8)); if(shift.start){const std=new Date(`${d.dateKey}T${shift.start}:00`); const actual=recTime(d.firstIn); if(actual>std) lateMinutes+=Math.round((actual-std)/60000)}}); const approvedOtHours=ots.reduce((s,o)=>s+Number(o.hours||0),0); const hourly=Number(e.hourlyRate||0)||Number(e.dailyRate||0)/8||Number(e.monthlySalary||0)/30/8; let basePay=0; if(e.payType==='monthly') basePay=Number(e.monthlySalary||0); else if(e.payType==='daily') basePay=workDays*Number(e.dailyRate||0); else basePay=regularHours*Number(e.hourlyRate||0); if(e.payCycle==='biweekly'&&e.payType==='monthly') basePay=Number(e.monthlySalary||0)/2; const otPay=approvedOtHours*hourly*Number(e.otMultiplier||1.5); const benefitsPay=benefits.reduce((s,b)=>s+(b.mode==='perWorkday'?Number(b.amount||0)*workDays:Number(b.amount||0)),0); const lateDeduction=lateMinutes*(hourly/60); const grossPay=basePay+otPay+benefitsPay; const netPay=grossPay-lateDeduction; return {employeeId:e.id,employeeCode:e.employeeCode,fullName:e.fullName,department:e.department||'',payType:e.payType||'hourly',payCycle:e.payCycle||'monthly',periodStart:start,periodEnd:end,workDays,regularHours,approvedOtHours,lateMinutes,basePay,otPay,benefitsPay,lateDeduction,grossPay,netPay}}
window.printSlip=employeeId=>{const r=lastPayrollRows.find(x=>x.employeeId===employeeId); if(!r)return; const w=window.open('','_blank'); w.document.write(`<html><head><title>Payroll Slip</title><style>body{font-family:Arial,sans-serif;padding:24px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px;text-align:left}.right{text-align:right}</style></head><body><h2>Payroll Slip</h2><p>${companySettings.companyName||''}</p><table><tr><th>พนักงาน</th><td>${safeText(r.employeeCode)} ${safeText(r.fullName)}</td></tr><tr><th>งวด</th><td>${r.periodStart} ถึง ${r.periodEnd}</td></tr><tr><th>วิธีจ่าย</th><td>${payTypeText(r.payType)} / ${r.payCycle==='biweekly'?'ราย 14 วัน':'รายเดือน'}</td></tr><tr><th>วันทำงาน</th><td>${r.workDays}</td></tr><tr><th>ชั่วโมงปกติ</th><td>${r.regularHours.toFixed(2)}</td></tr><tr><th>OT อนุมัติ</th><td>${r.approvedOtHours.toFixed(2)}</td></tr><tr><th>ฐานเงิน</th><td class="right">${money(r.basePay)}</td></tr><tr><th>OT</th><td class="right">${money(r.otPay)}</td></tr><tr><th>สวัสดิการ</th><td class="right">${money(r.benefitsPay)}</td></tr><tr><th>หักสาย</th><td class="right">${money(r.lateDeduction)}</td></tr><tr><th>สุทธิ</th><td class="right"><b>${money(r.netPay)}</b></td></tr></table><script>window.print()<\/script></body></html>`); w.document.close()};
function exportCsv(filename,rows){if(!rows.length)return toast('ไม่มีข้อมูลให้ export'); const headers=Object.keys(rows[0]); const csv=[headers.join(','),...rows.map(r=>headers.map(h=>'"'+String(r[h]??'').replace(/"/g,'""')+'"').join(','))].join('\n'); const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=filename; a.click(); URL.revokeObjectURL(a.href)}
function exportAttendance(){exportCsv(`attendance-detail-${todayKey()}.csv`,lastAttendanceRows.map(r=>({date:r.dateKey,employeeCode:r.employeeCode,fullName:r.fullName,clockIn:r.firstIn?displayTime(r.firstIn):'',clockOut:r.lastOut?displayTime(r.lastOut):'',workHours:r.workHours.toFixed(2),inGeofence:r.inGeofence,distanceMeters:r.distanceMeters||'',mapUrl:r.mapUrl||'',records:r.records.length})))}
function exportPayroll(){exportCsv(`payroll-detail-${todayKey()}.csv`,lastPayrollRows)}
async function loadAudit(){const snap=await db.collection('auditLogs').orderBy('createdAt','desc').limit(100).get(); $('auditList').innerHTML=snap.docs.map(d=>{const l=d.data(),dt=l.createdAt?.toDate?fmtDateTime(l.createdAt.toDate()):'-'; return `<div class="item"><b>${safeText(l.action)}</b><br><span class="muted">${dt} • ${safeText(l.actorCode)} ${safeText(l.actorName)}</span><br><code>${safeText(JSON.stringify(l.details||{}))}</code></div>`}).join('')||'<p class="muted">ยังไม่มี log</p>'}

function bind(){$('loginBtn').onclick=login; $('seedAdminBtn').onclick=seedAdmin; $('logoutBtn1').onclick=logout; $('logoutBtn2').onclick=logout; $('startCameraBtn').onclick=startCamera; $('captureBtn').onclick=()=>captureSelfie().catch(e=>toast(e.message,5000)); $('clockInBtn').onclick=()=>clock('IN'); $('clockOutBtn').onclick=()=>clock('OUT'); $('autoClockBtn').onclick=autoClock; $('refreshMyHistoryBtn').onclick=loadMyHistory; $('submitOtBtn').onclick=submitOt; $('submitLeaveBtn').onclick=submitLeave; document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab)); $('refreshTodayBtn').onclick=loadTodayAdmin; $('saveEmployeeBtn').onclick=saveEmployee; $('clearEmployeeBtn').onclick=clearEmployeeForm; $('loadAttendanceBtn').onclick=loadAttendance; $('saveCorrectionBtn').onclick=saveCorrection; $('exportAttendanceBtn').onclick=exportAttendance; $('saveShiftBtn').onclick=saveShift; $('clearShiftBtn').onclick=clearShift; $('loadOtBtn').onclick=loadOt; $('loadLeaveBtn').onclick=loadLeave; $('saveCalendarBtn').onclick=saveCalendar; $('saveBenefitBtn').onclick=saveBenefit; $('runPayrollBtn').onclick=runPayroll; $('exportPayrollBtn').onclick=exportPayroll; $('useCurrentLocationBtn').onclick=()=>useCurrentLocation().catch(e=>toast(e.message,5000)); $('saveSettingsBtn').onclick=saveSettings; $('clearAttendanceBtn').onclick=()=>deleteCollection('attendance'); $('clearAuditBtn').onclick=()=>deleteCollection('auditLogs'); $('loadAuditBtn').onclick=loadAudit; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault(); deferredPrompt=e; $('installBtn').classList.remove('hidden')}); $('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt(); deferredPrompt=null; $('installBtn').classList.add('hidden')}}}
if('serviceWorker'in navigator) navigator.serviceWorker.register('./service-worker.js').catch(console.warn);
bind(); initFirebase().catch(e=>{console.error(e); toast(e.message,6000); showPanel('setupPanel')});

/* =========================
   v2.2.0 overrides
   Payroll slip rules, payday settings, real calendar view, detailed CSV
   ========================= */
function addDays(d,n){const x=new Date(d); x.setDate(x.getDate()+n); return x}
function dateKeyOf(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function daysInMonth(y,m){return new Date(y,m+1,0).getDate()}
function parseDateKey(s){return new Date(`${s}T00:00:00`)}
function clampPayDay(y,m,day){return `${y}-${pad(m+1)}-${pad(Math.min(Number(day||30),daysInMonth(y,m)))}`}
function computeMonthlyPayDate(start,end){const ed=parseDateKey(end); return clampPayDay(ed.getFullYear(),ed.getMonth(),companySettings.monthlyPayDay||30)}
function computeBiweeklyPayDate(start,end){return end}
function computeCurrentPayPeriod(cycle='monthly'){
  const now=new Date();
  if(cycle==='biweekly'){
    const anchor=companySettings.biweeklyStartDate?parseDateKey(companySettings.biweeklyStartDate):new Date(now.getFullYear(),0,1);
    const diff=Math.floor((new Date(now.getFullYear(),now.getMonth(),now.getDate())-anchor)/86400000);
    const block=Math.floor(diff/14);
    const s=addDays(anchor,block*14);
    const e=addDays(s,13);
    return {start:dateKeyOf(s),end:dateKeyOf(e),payDate:dateKeyOf(e)};
  }
  const y=now.getFullYear(), m=now.getMonth();
  return {start:`${y}-${pad(m+1)}-01`,end:`${y}-${pad(m+1)}-${pad(daysInMonth(y,m))}`,payDate:clampPayDay(y,m,companySettings.monthlyPayDay||30)};
}
function getPayDateForRow(row){return row.payCycle==='biweekly'?computeBiweeklyPayDate(row.periodStart,row.periodEnd):computeMonthlyPayDate(row.periodStart,row.periodEnd)}
function canPrintSlip(row){
  // ตาม requirement: รายวัน/รายชั่วโมงพิมพ์ได้หลังมีเวลาออกงาน, รายเดือนแสดงรายละเอียดแต่ปิดพิมพ์
  return row.payType!=='monthly' && row.hasClosedWork!==false;
}
function slipDisabledReason(row){
  if(row.payType==='monthly') return 'รายเดือน: แสดงรายละเอียดได้ แต่ปิดการพิมพ์ตามนโยบาย';
  if(row.hasClosedWork===false) return 'ยังไม่มีเวลาออกงาน จึงยังพิมพ์ไม่ได้';
  return '';
}
async function fetchCalendarEvents(start,end){
  const snap=await db.collection('companyCalendar').get();
  return snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>(x.dateKey||'')>=start&&(x.dateKey||'')<=end);
}
function buildPaydayEvents(year,month){
  const events=[];
  const monthly=clampPayDay(year,month,companySettings.monthlyPayDay||30);
  events.push({dateKey:monthly,title:'วันเงินออกรายเดือน',type:'payday',isPaid:true,system:true});
  if(companySettings.biweeklyStartDate){
    let d=parseDateKey(companySettings.biweeklyStartDate);
    const first=new Date(year,month,1), last=new Date(year,month,daysInMonth(year,month));
    while(d<first) d=addDays(d,14);
    while(d<=last){events.push({dateKey:dateKeyOf(d),title:'วันเงินออกราย 14 วัน',type:'payday',isPaid:true,system:true}); d=addDays(d,14)}
  }
  return events;
}
function renderMonthGrid(targetId,events=[],employee=null,monthValue=null){
  const target=$(targetId); if(!target) return;
  const base=monthValue?new Date(`${monthValue}-01T00:00:00`):new Date();
  const y=base.getFullYear(), m=base.getMonth(), first=new Date(y,m,1), total=daysInMonth(y,m), startDow=first.getDay();
  const names=['อา','จ','อ','พ','พฤ','ศ','ส'];
  const byDate={}; [...events,...buildPaydayEvents(y,m)].forEach(e=>{(byDate[e.dateKey]||=[]).push(e)});
  let html=names.map(n=>`<div class="cal-head">${n}</div>`).join('');
  for(let i=0;i<startDow;i++) html+=`<div class="cal-day off"></div>`;
  for(let day=1;day<=total;day++){
    const key=`${y}-${pad(m+1)}-${pad(day)}`;
    const dow=new Date(y,m,day).getDay();
    const today=key===todayKey();
    const evs=byDate[key]||[];
    const isHoliday=evs.some(e=>e.type==='holiday');
    const workLabel=(!isHoliday && dow!==0) ? (employee?.shiftName||'วันทำงาน') : '';
    html+=`<div class="cal-day ${today?'today':''} ${dow===0?'off':''}"><div class="cal-num">${day}</div>${workLabel?`<span class="cal-event event">${safeText(workLabel)}</span>`:''}${evs.map(e=>`<span class="cal-event ${safeText(e.type||'event')}">${safeText(e.title||e.type)}</span>`).join('')}</div>`;
  }
  target.innerHTML=html;
}
async function loadUserCalendar(){
  try{
    const now=new Date(); const start=`${now.getFullYear()}-${pad(now.getMonth()+1)}-01`; const end=`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(daysInMonth(now.getFullYear(),now.getMonth()))}`;
    const events=await fetchCalendarEvents(start,end);
    await getShifts(); const sh=getShift(currentEmployee?.shiftId); renderMonthGrid('userCalendarGrid',events,{...currentEmployee,shiftName:sh.name});
  }catch(e){console.error(e); if($('userCalendarGrid')) $('userCalendarGrid').innerHTML=`<p class="muted">โหลดปฏิทินไม่สำเร็จ: ${safeText(e.message)}</p>`}
}
async function loadCalendar(){
  const mv=$('calMonth')?.value || todayKey().slice(0,7);
  const [y,m]=mv.split('-').map(Number); const start=`${y}-${pad(m)}-01`, end=`${y}-${pad(m)}-${pad(daysInMonth(y,m-1))}`;
  const events=await fetchCalendarEvents(start,end);
  renderMonthGrid('calendarGrid',events,null,mv);
  $('calendarList').innerHTML=events.sort((a,b)=>String(a.dateKey).localeCompare(String(b.dateKey))).map(c=>`<div class="item"><b>${safeText(c.dateKey)} - ${safeText(c.title)}</b><br><span class="muted">${safeText(c.type)} • ${c.isPaid?'มีค่าจ้าง':'ไม่มีค่าจ้าง'}</span><div class="row-actions"><button class="danger" onclick="deleteCalendar('${c.id}')">ลบ</button></div></div>`).join('')||'<p class="muted">ยังไม่มีรายการปฏิทิน</p>';
}
async function showEmployee(){
  showPanel('employeePanel');
  $('empName').textContent=currentEmployee.fullName;
  $('empDetail').textContent=`${currentEmployee.employeeCode} • ${currentEmployee.department||'-'} • ${currentEmployee.position||'-'} • ${payTypeText(currentEmployee.payType)} / ${currentEmployee.payCycle==='biweekly'?'ราย 14 วัน':'รายเดือน'}`;
  setUserDefaultDates();
  await refreshMyStatus();
  await loadMyHistory();
  await loadUserCalendar();
  await loadUserSlipPreview();
}
function renderDailyItem(r,admin){
  const img=r.photoURL?`<img src="${r.photoURL}" class="thumb" loading="lazy">`:'';
  const geo=r.inGeofence===null||r.inGeofence===undefined?'':`<span class="badge ${r.inGeofence?'good':'bad'}">${r.inGeofence?'ในพื้นที่':'นอกพื้นที่'} ${r.distanceMeters?Math.round(r.distanceMeters)+'m':''}</span>`;
  const userPrint=(!admin && currentEmployee && (currentEmployee.payType==='daily'||currentEmployee.payType==='hourly') && r.lastOut) ? `<button class="secondary" onclick="printDailySlip('${r.dateKey}')">พิมพ์ Slip รายวัน</button>` : '';
  const userMonthly=(!admin && currentEmployee?.payType==='monthly') ? `<span class="disabled-note">รายเดือนดูรายละเอียดได้ แต่ปิดพิมพ์</span>` : '';
  return `<div class="item"><div>${img}<b>${safeText(r.employeeCode)} - ${safeText(r.fullName)}</b><br><span class="muted">${r.dateKey} • เข้า ${r.firstIn?displayTime(r.firstIn).slice(11):'-'} • ออก ${r.lastOut?displayTime(r.lastOut).slice(11):'-'} • ${r.workHours.toFixed(2)} ชม.</span><br>${geo} <span class="badge">${r.records.length} รายการ</span></div><div class="row-actions">${r.mapUrl?`<a href="${r.mapUrl}" target="_blank"><button class="ghost">แผนที่</button></a>`:''}${userPrint}${userMonthly}${admin?`<button class="ghost" onclick="copyText('${r.employeeId}')">คัดลอก ID</button>`:''}</div></div>`;
}
async function loadMyHistory(){
  try{const rows=await getAttendanceRows(currentEmployee.id,null,null); const daily=pairAttendance(rows).slice(0,30); $('myHistory').innerHTML=daily.map(r=>renderDailyItem(r,false)).join('')||'<p class="muted">ยังไม่มีประวัติ</p>'}
  catch(e){console.error(e); $('myHistory').innerHTML=`<p class="muted">โหลดประวัติไม่สำเร็จ: ${safeText(e.message)}</p>`}
}
async function loadUserSlipPreview(){
  const box=$('userSlipList'); if(!box||!currentEmployee) return;
  try{
    const rows=await getAttendanceRows(currentEmployee.id,null,null); await getShifts(); const daily=pairAttendance(rows).slice(0,14);
    if(!daily.length){box.innerHTML='<p class="muted">ยังไม่มีข้อมูลสำหรับ slip</p>'; return}
    box.innerHTML=daily.map(d=>{
      const tmp=calcPayroll(currentEmployee,d.records,[],[],d.dateKey,d.dateKey);
      tmp.hasClosedWork=!!d.lastOut; tmp.dailyDate=d.dateKey;
      const print=canPrintSlip(tmp)?`<button class="secondary" onclick="printDailySlip('${d.dateKey}')">พิมพ์ Slip</button>`:`<span class="disabled-note">${slipDisabledReason(tmp)}</span>`;
      return `<div class="item"><b>${d.dateKey}</b><br><span class="muted">เข้า ${d.firstIn?displayTime(d.firstIn).slice(11):'-'} • ออก ${d.lastOut?displayTime(d.lastOut).slice(11):'-'} • ชั่วโมง ${d.workHours.toFixed(2)}</span><br>ยอดประมาณการ: <b>${money(tmp.netPay)} บาท</b><div class="row-actions">${print}</div></div>`;
    }).join('');
  }catch(e){box.innerHTML=`<p class="muted">โหลด slip ไม่สำเร็จ: ${safeText(e.message)}</p>`}
}
window.printDailySlip=async function(dateKey){
  const rows=await getAttendanceRows(currentEmployee.id,dateKey,dateKey); await getShifts(); const d=pairAttendance(rows)[0]; if(!d||!d.lastOut){toast('ยังไม่มีเวลาออกงาน จึงพิมพ์ไม่ได้'); return}
  const r=calcPayroll(currentEmployee,d.records,[],await getBenefits(),dateKey,dateKey); r.hasClosedWork=true; r.dailyDate=dateKey; printSlipHtml(r,true);
}
function fillSettings(){
  $('setCompany').value=companySettings.companyName||''; $('setRadius').value=companySettings.radiusMeters||100; $('setLat').value=companySettings.officeLat||''; $('setLng').value=companySettings.officeLng||'';
  if($('setMonthlyPayDay')) $('setMonthlyPayDay').value=companySettings.monthlyPayDay||30;
  if($('setBiweeklyStart')) $('setBiweeklyStart').value=companySettings.biweeklyStartDate||todayKey();
}
async function saveSettings(){
  companySettings={companyName:$('setCompany').value.trim()||'ระบบลงเวลาออนไลน์',radiusMeters:Number($('setRadius').value||100),officeLat:$('setLat').value?Number($('setLat').value):null,officeLng:$('setLng').value?Number($('setLng').value):null,monthlyPayDay:Number($('setMonthlyPayDay')?.value||30),biweeklyStartDate:$('setBiweeklyStart')?.value||todayKey()};
  await db.collection('settings').doc('company').set({...companySettings,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}); await logAudit('UPDATE_SETTINGS',companySettings); await loadSettings(); toast('บันทึกตั้งค่าแล้ว'); loadCalendar().catch(()=>{});
}
function setDefaultDates(){
  const t=todayKey(); ['attStart','attEnd','payStart','payEnd','corrDate','calDate'].forEach(id=>{if($(id)) $(id).value=t}); if($('payStart')) $('payStart').value=t.slice(0,8)+'01'; if($('attStart')) $('attStart').value=t.slice(0,8)+'01'; if($('calMonth')) $('calMonth').value=t.slice(0,7); if($('setBiweeklyStart')&&!$('setBiweeklyStart').value) $('setBiweeklyStart').value=t;
}
function setCurrentPayPeriod(){const p=computeCurrentPayPeriod('monthly'); $('payStart').value=p.start; $('payEnd').value=p.end; toast(`ตั้งงวด ${p.start} ถึง ${p.end} / วันเงินออก ${p.payDate}`)}
async function runPayroll(){
  const start=$('payStart').value,end=$('payEnd').value; const [empSnap,attSnap,otSnap,benefitsSnap]=await Promise.all([db.collection('employees').get(),db.collection('attendance').where('dateKey','>=',start).where('dateKey','<=',end).get(),db.collection('otRequests').where('dateKey','>=',start).where('dateKey','<=',end).where('status','==','approved').get(),db.collection('benefits').where('active','==',true).get()]);
  const employees=empSnap.docs.map(d=>({id:d.id,...d.data()})).filter(e=>e.role!=='admin'&&e.active!==false); const records=attSnap.docs.map(d=>normalizeAttendance(d.id,d.data())); const ots=otSnap.docs.map(d=>({id:d.id,...d.data()})); const benefits=benefitsSnap.docs.map(d=>({id:d.id,...d.data()})); await getShifts();
  lastPayrollRows=employees.map(e=>calcPayroll(e,records.filter(r=>r.employeeId===e.id||r.employeeCode===e.employeeCode),ots.filter(o=>o.employeeId===e.id||o.employeeCode===e.employeeCode),benefits,start,end)).filter(r=>r.workDays>0||r.basePay>0);
  $('payrollList').innerHTML=lastPayrollRows.map(r=>{const dis=slipDisabledReason(r); const print=canPrintSlip(r)?`<button class="secondary" onclick="printSlip('${r.employeeId}')">พิมพ์ Slip</button>`:`<span class="disabled-note">${dis}</span>`; return `<div class="item"><b>${safeText(r.employeeCode)} ${safeText(r.fullName)}</b><br><span class="muted">${payTypeText(r.payType)} • ${r.payCycle==='biweekly'?'ราย 14 วัน':'รายเดือน'} • งวด ${r.periodStart} ถึง ${r.periodEnd} • วันเงินออก ${r.payDate}</span><br><span class="muted">วันทำงาน ${r.workDays} • ปกติ ${r.regularHours.toFixed(2)} ชม. • OT อนุมัติ ${r.approvedOtHours.toFixed(2)} ชม. • สาย ${r.lateMinutes} นาที</span><br>ฐาน ${money(r.basePay)} + OT ${money(r.otPay)} + สวัสดิการ ${money(r.benefitsPay)} - หักสาย ${money(r.lateDeduction)} = <b>${money(r.netPay)} บาท</b><div class="row-actions">${print}</div></div>`}).join('')||'<p class="muted">ไม่พบข้อมูลเงินเดือน</p>';
}
function calcPayroll(e,rows,ots,benefits,start,end){
  const daily=pairAttendance(rows); const shift=getShift(e.shiftId); let workDays=0,regularHours=0,lateMinutes=0; const dailyDetails=[];
  daily.forEach(d=>{if(!d.firstIn||!d.lastOut){dailyDetails.push({dateKey:d.dateKey,clockIn:d.firstIn?displayTime(d.firstIn):'',clockOut:d.lastOut?displayTime(d.lastOut):'',workHours:d.workHours,closed:false}); return} workDays++; const hrs=d.workHours; const regular=Math.min(hrs,Number(shift.regularHours||8)); regularHours+=regular; let late=0; if(shift.start){const std=new Date(`${d.dateKey}T${shift.start}:00`); const actual=recTime(d.firstIn); if(actual>std) late=Math.round((actual-std)/60000)} lateMinutes+=late; dailyDetails.push({dateKey:d.dateKey,clockIn:displayTime(d.firstIn),clockOut:displayTime(d.lastOut),workHours:hrs,regularHours:regular,lateMinutes:late,closed:true})});
  const approvedOtHours=ots.reduce((s,o)=>s+Number(o.hours||0),0); const hourly=Number(e.hourlyRate||0)||Number(e.dailyRate||0)/8||Number(e.monthlySalary||0)/30/8; let basePay=0; if(e.payType==='monthly') basePay=Number(e.monthlySalary||0); else if(e.payType==='daily') basePay=workDays*Number(e.dailyRate||0); else basePay=regularHours*Number(e.hourlyRate||0); if(e.payCycle==='biweekly'&&e.payType==='monthly') basePay=Number(e.monthlySalary||0)/2;
  const otPay=approvedOtHours*hourly*Number(e.otMultiplier||1.5); const benefitLines=benefits.map(b=>({name:b.name||'',mode:b.mode,amount:Number(b.amount||0),total:b.mode==='perWorkday'?Number(b.amount||0)*workDays:Number(b.amount||0)})); const benefitsPay=benefitLines.reduce((s,b)=>s+b.total,0); const lateDeduction=lateMinutes*(hourly/60); const grossPay=basePay+otPay+benefitsPay; const netPay=grossPay-lateDeduction; const payCycle=e.payCycle||'monthly'; const payDate=payCycle==='biweekly'?computeBiweeklyPayDate(start,end):computeMonthlyPayDate(start,end); const hasClosedWork=daily.some(x=>x.lastOut);
  return {employeeId:e.id,employeeCode:e.employeeCode,fullName:e.fullName,department:e.department||'',payType:e.payType||'hourly',payCycle,periodStart:start,periodEnd:end,payDate,workDays,regularHours,approvedOtHours,lateMinutes,hourlyRate:hourly,dailyRate:Number(e.dailyRate||0),monthlySalary:Number(e.monthlySalary||0),basePay,otPay,benefitsPay,benefitLines,lateDeduction,grossPay,netPay,dailyDetails,hasClosedWork};
}
function printSlipHtml(r,isUser=false){
  const dailyRows=(r.dailyDetails||[]).map(d=>`<tr><td>${safeText(d.dateKey)}</td><td>${safeText(d.clockIn||'')}</td><td>${safeText(d.clockOut||'')}</td><td class="right">${Number(d.workHours||0).toFixed(2)}</td><td class="right">${Number(d.lateMinutes||0)}</td></tr>`).join('');
  const benefitRows=(r.benefitLines||[]).map(b=>`<tr><td>${safeText(b.name)}</td><td>${b.mode==='perWorkday'?'ตามวันทำงาน':'Fix รายเดือน'}</td><td class="right">${money(b.total)}</td></tr>`).join('')||'<tr><td colspan="3">-</td></tr>';
  const w=window.open('','_blank'); w.document.write(`<html><head><title>Payroll Slip</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial,sans-serif;padding:24px;color:#111827}h2,h3,p{margin:0 0 10px}table{width:100%;border-collapse:collapse;margin:10px 0}td,th{border:1px solid #ddd;padding:8px;text-align:left}.right{text-align:right}.muted{color:#64748b}@media print{button{display:none}}</style></head><body><h2>Payroll Slip</h2><p>${safeText(companySettings.companyName||'')}</p><p class="muted">${isUser?'พนักงานพิมพ์เอง':'ออกโดยผู้ดูแลระบบ'}</p><table><tr><th>พนักงาน</th><td>${safeText(r.employeeCode)} ${safeText(r.fullName)}</td></tr><tr><th>งวด</th><td>${r.periodStart} ถึง ${r.periodEnd}</td></tr><tr><th>วันเงินออก</th><td>${r.payDate}</td></tr><tr><th>วิธีจ่าย</th><td>${payTypeText(r.payType)} / ${r.payCycle==='biweekly'?'ราย 14 วัน':'รายเดือน'}</td></tr></table><h3>รายละเอียดเวลา</h3><table><tr><th>วันที่</th><th>เข้า</th><th>ออก</th><th>ชม.</th><th>สาย(นาที)</th></tr>${dailyRows}</table><h3>สรุปรายได้</h3><table><tr><th>ฐานเงิน</th><td class="right">${money(r.basePay)}</td></tr><tr><th>OT อนุมัติ ${r.approvedOtHours.toFixed(2)} ชม.</th><td class="right">${money(r.otPay)}</td></tr><tr><th>สวัสดิการ</th><td class="right">${money(r.benefitsPay)}</td></tr><tr><th>หักสาย</th><td class="right">${money(r.lateDeduction)}</td></tr><tr><th>สุทธิ</th><td class="right"><b>${money(r.netPay)}</b></td></tr></table><h3>สวัสดิการ</h3><table><tr><th>ชื่อ</th><th>วิธีคิด</th><th>ยอด</th></tr>${benefitRows}</table><button onclick="window.print()">พิมพ์</button><script>setTimeout(()=>window.print(),500)<\/script></body></html>`); w.document.close();
}
window.printSlip=function(employeeId){const r=lastPayrollRows.find(x=>x.employeeId===employeeId); if(!r)return; if(!canPrintSlip(r)){toast(slipDisabledReason(r),5000); return} printSlipHtml(r,false)}
function exportAttendance(){
  const rows=[]; lastAttendanceRows.forEach(r=>{rows.push({recordType:'DAILY_SUMMARY',date:r.dateKey,employeeCode:r.employeeCode,fullName:r.fullName,clockIn:r.firstIn?displayTime(r.firstIn):'',clockOut:r.lastOut?displayTime(r.lastOut):'',workHours:r.workHours.toFixed(2),inGeofence:r.inGeofence,distanceMeters:r.distanceMeters||'',mapUrl:r.mapUrl||'',photoMode:r.photoURL?'base64/firestore':'',recordCount:r.records.length}); r.records.forEach(x=>rows.push({recordType:'RAW',date:x.dateKey,employeeCode:x.employeeCode,fullName:x.fullName,type:x.type,time:displayTime(x),source:x.source||'',lat:x.latitude||'',lng:x.longitude||'',accuracy:x.accuracy||'',mapUrl:x.mapUrl||'',inGeofence:x.inGeofence,distanceMeters:x.distanceMeters||'',reason:x.reason||''}))}); exportCsv(`attendance-detailed-${todayKey()}.csv`,rows)
}
function exportPayroll(){exportCsv(`payroll-detailed-${todayKey()}.csv`,lastPayrollRows.map(r=>({employeeCode:r.employeeCode,fullName:r.fullName,department:r.department,payType:payTypeText(r.payType),payCycle:r.payCycle==='biweekly'?'ราย 14 วัน':'รายเดือน',periodStart:r.periodStart,periodEnd:r.periodEnd,payDate:r.payDate,workDays:r.workDays,regularHours:r.regularHours.toFixed(2),approvedOtHours:r.approvedOtHours.toFixed(2),lateMinutes:r.lateMinutes,hourlyRate:r.hourlyRate,dailyRate:r.dailyRate,monthlySalary:r.monthlySalary,basePay:r.basePay,otPay:r.otPay,benefitsPay:r.benefitsPay,lateDeduction:r.lateDeduction,grossPay:r.grossPay,netPay:r.netPay,printAllowed:canPrintSlip(r),printNote:slipDisabledReason(r)})))}
function exportPayrollSlipCsv(){
  const rows=[]; lastPayrollRows.forEach(r=>{rows.push({lineType:'SUMMARY',employeeCode:r.employeeCode,fullName:r.fullName,periodStart:r.periodStart,periodEnd:r.periodEnd,payDate:r.payDate,payType:payTypeText(r.payType),payCycle:r.payCycle,description:'NET_PAY',amount:r.netPay}); (r.dailyDetails||[]).forEach(d=>rows.push({lineType:'DAY',employeeCode:r.employeeCode,fullName:r.fullName,date:d.dateKey,clockIn:d.clockIn,clockOut:d.clockOut,workHours:d.workHours,lateMinutes:d.lateMinutes})); (r.benefitLines||[]).forEach(b=>rows.push({lineType:'BENEFIT',employeeCode:r.employeeCode,fullName:r.fullName,description:b.name,mode:b.mode,amount:b.total}))}); exportCsv(`payroll-slip-lines-${todayKey()}.csv`,rows)
}
function bind(){
  const on=(id,fn)=>{if($(id)) $(id).onclick=fn};
  on('loginBtn',login); on('seedAdminBtn',seedAdmin); on('logoutBtn1',logout); on('logoutBtn2',logout); on('startCameraBtn',startCamera); on('captureBtn',()=>captureSelfie().catch(e=>toast(e.message,5000))); on('clockInBtn',()=>clock('IN')); on('clockOutBtn',()=>clock('OUT')); on('autoClockBtn',autoClock); on('refreshMyHistoryBtn',loadMyHistory); on('refreshUserCalendarBtn',loadUserCalendar); on('refreshUserSlipBtn',loadUserSlipPreview); on('submitOtBtn',submitOt); on('submitLeaveBtn',submitLeave);
  document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
  on('refreshTodayBtn',loadTodayAdmin); on('saveEmployeeBtn',saveEmployee); on('clearEmployeeBtn',clearEmployeeForm); on('loadAttendanceBtn',loadAttendance); on('saveCorrectionBtn',saveCorrection); on('exportAttendanceBtn',exportAttendance); on('saveShiftBtn',saveShift); on('clearShiftBtn',clearShift); on('loadOtBtn',loadOt); on('loadLeaveBtn',loadLeave); on('saveCalendarBtn',saveCalendar); on('loadCalendarBtn',loadCalendar); on('saveBenefitBtn',saveBenefit); on('runPayrollBtn',runPayroll); on('exportPayrollBtn',exportPayroll); on('exportPayrollSlipCsvBtn',exportPayrollSlipCsv); on('setCurrentPayPeriodBtn',setCurrentPayPeriod); on('useCurrentLocationBtn',()=>useCurrentLocation().catch(e=>toast(e.message,5000))); on('saveSettingsBtn',saveSettings); on('clearAttendanceBtn',()=>deleteCollection('attendance')); on('clearAuditBtn',()=>deleteCollection('auditLogs')); on('loadAuditBtn',loadAudit);
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn')?.classList.remove('hidden')}); on('installBtn',async()=>{if(deferredPrompt){deferredPrompt.prompt(); deferredPrompt=null; $('installBtn')?.classList.add('hidden')}})
}
