import { db } from "../core/firebase.js";
import { safeText, todayKey, fmtDateTime, distanceMeters } from "../core/utils.js";

let mediaStream = null, capturedDataUrl = null, currentPosition = null;
let companySettings = { officeLat: null, officeLng: null, radiusMeters: 100, geofenceMode: "warning" };

export async function renderAttendanceModule(container, employee, mode="employee"){
  await loadSettings();
  container.innerHTML=`
    <div class="module-head"><div><h2>${mode==="admin"?"รายการลงเวลา":"ลงเวลา"}</h2><p class="muted">Selfie + GPS + Geofence</p></div><button id="reloadAttendanceBtn" class="secondary compact">โหลดใหม่</button></div>
    ${mode==="employee"?employeeClockUi():adminAttendanceUi()}
    <div id="attendanceDetailModal" class="modal hidden"><div class="modal-backdrop" id="closeDetailBackdrop"></div><div class="modal-card"><div class="modal-head"><div><h2 id="detailTitle">รายละเอียดการลงเวลา</h2><p id="detailSub" class="muted"></p></div><button id="closeDetailBtn" class="secondary compact">ปิด</button></div><div id="detailBody"></div></div></div>`;
  document.getElementById("reloadAttendanceBtn").onclick=()=>renderAttendanceModule(container,employee,mode);
  document.getElementById("closeDetailBtn").onclick=closeDetail; document.getElementById("closeDetailBackdrop").onclick=closeDetail;
  if(mode==="employee"){
    document.getElementById("startCameraBtn").onclick=startCamera;
    document.getElementById("captureBtn").onclick=()=>captureSelfie(employee).catch(showErr);
    document.getElementById("clockInBtn").onclick=()=>clock(employee,"IN").catch(showErr);
    document.getElementById("clockOutBtn").onclick=()=>clock(employee,"OUT").catch(showErr);
    document.getElementById("autoClockBtn").onclick=()=>autoClock(employee).catch(showErr);
    await loadMyAttendance(employee);
  } else {
    document.getElementById("attStart").value=todayKey();
    document.getElementById("attEnd").value=todayKey();
    document.getElementById("loadAdminAttendanceBtn").onclick=loadAdminAttendance;
    await loadAdminAttendance();
  }
}
function employeeClockUi(){return `<div class="clock-layout"><section class="card clock-card"><video id="camera" autoplay playsinline muted></video><canvas id="snapshot" class="hidden"></canvas><img id="preview" class="preview hidden"><p id="gpsStatus" class="muted small"></p><p id="clockMsg" class="message"></p><div class="actions-grid"><button id="startCameraBtn" class="secondary">เปิดกล้อง</button><button id="captureBtn" class="secondary">ถ่ายรูป + GPS</button><button id="clockInBtn" class="good">เข้างาน</button><button id="clockOutBtn" class="danger">ออกงาน</button><button id="autoClockBtn" class="primary">อัตโนมัติ</button></div></section><section class="card wide"><h3>ประวัติวันนี้</h3><div id="myAttendanceList" class="list"></div></section></div>`}
function adminAttendanceUi(){return `<section class="card wide"><div class="filters"><input id="attStart" type="date"><input id="attEnd" type="date"><button id="loadAdminAttendanceBtn" class="primary compact">โหลด</button></div><div id="adminAttendanceList" class="list"></div></section>`}
async function loadSettings(){try{const doc=await db.collection("settings").doc("company").get();if(doc.exists) companySettings={...companySettings,...doc.data()}}catch(e){}}
function showErr(err){const msg=document.getElementById("clockMsg"); if(msg) msg.textContent="ผิดพลาด: "+err.message; else alert(err.message)}
async function startCamera(){ if(mediaStream)mediaStream.getTracks().forEach(t=>t.stop()); mediaStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false}); document.getElementById("camera").srcObject=mediaStream; }
async function getGPS(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error("อุปกรณ์นี้ไม่รองรับ GPS"));navigator.geolocation.getCurrentPosition(pos=>{currentPosition={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy};const gps=document.getElementById("gpsStatus");if(gps)gps.textContent=`GPS: ${currentPosition.lat.toFixed(6)}, ${currentPosition.lng.toFixed(6)} ±${Math.round(currentPosition.accuracy)}m`;resolve(currentPosition)},err=>reject(new Error(err.message||"ไม่ได้รับอนุญาตตำแหน่ง")),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
async function captureSelfie(employee){const video=document.getElementById("camera"); if(!mediaStream)throw new Error("กรุณาเปิดกล้องก่อน"); await getGPS(); const sourceW=video.videoWidth||720, sourceH=video.videoHeight||960, maxW=320, scale=Math.min(1,maxW/sourceW), w=Math.round(sourceW*scale), h=Math.round(sourceH*scale); const canvas=document.getElementById("snapshot"); canvas.width=w; canvas.height=h; const ctx=canvas.getContext("2d"); ctx.drawImage(video,0,0,w,h); ctx.fillStyle="rgba(0,0,0,.68)"; ctx.fillRect(0,h-82,w,82); ctx.fillStyle="#fff"; ctx.font="12px sans-serif"; [employee.fullName||employee.employeeCode,employee.employeeCode||"",fmtDateTime(new Date()),`GPS: ${currentPosition.lat.toFixed(6)}, ${currentPosition.lng.toFixed(6)}`].forEach((s,i)=>ctx.fillText(s,8,h-64+i*18)); capturedDataUrl=canvas.toDataURL("image/jpeg",0.28); const preview=document.getElementById("preview"); preview.src=capturedDataUrl; preview.classList.remove("hidden"); document.getElementById("clockMsg").textContent="ถ่ายรูปและดึงตำแหน่งแล้ว"}
function geo(){let dist=null,inGeo=null;if(companySettings.officeLat&&companySettings.officeLng&&currentPosition){dist=distanceMeters(currentPosition.lat,currentPosition.lng,Number(companySettings.officeLat),Number(companySettings.officeLng));inGeo=dist<=Number(companySettings.radiusMeters||100)}return{dist,inGeo}}
async function clock(employee,type){ if(!capturedDataUrl)throw new Error("ต้องถ่ายรูปก่อนลงเวลา"); if(!currentPosition)await getGPS(); const {dist,inGeo}=geo(),mode=companySettings.geofenceMode||"warning"; if(mode==="strict"&&inGeo===false)throw new Error(`คุณอยู่นอกพื้นที่ ${Math.round(dist)} เมตร ไม่สามารถลงเวลาได้`); const now=new Date(); await db.collection("attendance").add({employeeId:employee.id,employeeCode:employee.employeeCode,fullName:employee.fullName,department:employee.department||"",position:employee.position||"",type,source:"EMPLOYEE",dateKey:todayKey(),createdAt:firebase.firestore.FieldValue.serverTimestamp(),clientTime:now.toISOString(),clientTimeText:fmtDateTime(now),photoMode:"base64",photoURL:capturedDataUrl,latitude:currentPosition.lat,longitude:currentPosition.lng,accuracy:currentPosition.accuracy,mapUrl:`https://maps.google.com/?q=${currentPosition.lat},${currentPosition.lng}`,distanceMeters:dist,inGeofence:inGeo,geofenceMode:mode,userAgent:navigator.userAgent}); capturedDataUrl=null; currentPosition=null; document.getElementById("preview").classList.add("hidden"); document.getElementById("gpsStatus").textContent=""; document.getElementById("clockMsg").textContent="บันทึกสำเร็จ"; await loadMyAttendance(employee)}
async function autoClock(employee){const snap=await db.collection("attendance").where("employeeId","==",employee.id).where("dateKey","==",todayKey()).get(); const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0)); const last=rows.at(-1); await clock(employee,!last||last.type==="OUT"?"IN":"OUT")}
async function loadMyAttendance(employee){const list=document.getElementById("myAttendanceList"); list.innerHTML=`<div class="empty-state"><p>กำลังโหลด...</p></div>`; try{const snap=await db.collection("attendance").where("employeeId","==",employee.id).where("dateKey","==",todayKey()).get(); const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)); list.innerHTML=rows.length?rows.map(itemCard).join(""):`<div class="empty-state"><p>วันนี้ยังไม่มีรายการ</p></div>`; rows.forEach(r=>document.getElementById(`att-${r.id}`).onclick=()=>openDetail(r))}catch(err){list.innerHTML=`<div class="empty-state error-text"><p>${safeText(err.message)}</p></div>`}}
async function loadAdminAttendance(){const list=document.getElementById("adminAttendanceList"),start=document.getElementById("attStart").value,end=document.getElementById("attEnd").value;list.innerHTML=`<div class="empty-state"><p>กำลังโหลด...</p></div>`;try{const snap=await db.collection("attendance").where("dateKey",">=",start).where("dateKey","<=",end).get();const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));list.innerHTML=rows.length?rows.map(itemCard).join(""):`<div class="empty-state"><p>ไม่พบข้อมูล</p></div>`;rows.forEach(r=>document.getElementById(`att-${r.id}`).onclick=()=>openDetail(r))}catch(err){list.innerHTML=`<div class="empty-state error-text"><p>${safeText(err.message)}</p></div>`}}
function itemCard(r){const label=r.type==="IN"?"เข้างาน":"ออกงาน",geo=r.inGeofence===false?"นอกพื้นที่":r.inGeofence===true?"ในพื้นที่":"ไม่ตรวจ",time=r.createdAt?.toDate?fmtDateTime(r.createdAt.toDate()):(r.clientTimeText||r.clientTime||"-");return `<article id="att-${r.id}" class="attendance-card clickable">${r.photoURL?`<img src="${r.photoURL}" class="att-thumb" loading="lazy">`:`<div class="att-thumb empty-photo">ไม่มีรูป</div>`}<div><h3>${safeText(r.employeeCode)} • ${safeText(r.fullName)}</h3><p>${label} • ${safeText(time)}</p><div class="badges"><span class="badge">${safeText(r.dateKey)}</span><span class="badge ${r.inGeofence===false?"bad":"good"}">${geo}</span>${r.distanceMeters?`<span class="badge">${Math.round(r.distanceMeters)}m</span>`:""}</div></div></article>`}
function openDetail(r){const time=r.createdAt?.toDate?fmtDateTime(r.createdAt.toDate()):(r.clientTimeText||r.clientTime||"-"),label=r.type==="IN"?"เข้างาน":"ออกงาน";document.getElementById("detailTitle").textContent=`${r.employeeCode} • ${r.fullName}`;document.getElementById("detailSub").textContent=`${label} • ${time}`;document.getElementById("detailBody").innerHTML=`${r.photoURL?`<img src="${r.photoURL}" class="detail-photo">`:`<p class="muted">ไม่มีรูป</p>`}<div class="detail-grid"><div class="detail-row"><b>วันที่/เวลา</b>${safeText(r.dateKey)}<br>${safeText(time)}</div><div class="detail-row"><b>GPS</b>Lat: ${safeText(r.latitude??"-")}<br>Lng: ${safeText(r.longitude??"-")}<br>Accuracy: ${safeText(r.accuracy?Math.round(r.accuracy)+"m":"-")}</div><div class="detail-row"><b>แผนที่</b>${r.mapUrl?`<a href="${r.mapUrl}" target="_blank">เปิด Google Maps</a>`:"-"}</div></div>`;document.getElementById("attendanceDetailModal").classList.remove("hidden")}
function closeDetail(){document.getElementById("attendanceDetailModal").classList.add("hidden")}
